ID_STR_ = {'statuses': [
    {'created_at': 'Sat May 12 15:29:45 +0000 2018', 'id': 995325161183350785, 'id_str': '995325161183350785',
     'text': 'RT @rafaelsolis: #Bitcoin prices through the years $0.0001 to $8,500 2009-2018 #crypto #cryptocurreny #ether #litecoin https://t.co/2iesH6n…',
     'truncated': False, 'entities': {
        'hashtags': [{'text': 'Bitcoin', 'indices': [17, 25]}, {'text': 'crypto', 'indices': [79, 86]},
                     {'text': 'cryptocurreny', 'indices': [87, 101]}, {'text': 'ether', 'indices': [102, 108]},
                     {'text': 'litecoin', 'indices': [109, 118]}], 'symbols': [], 'user_mentions': [
            {'screen_name': 'rafaelsolis', 'name': 'Rafael Solis', 'id': 15223998, 'id_str': '15223998',
             'indices': [3, 15]}], 'urls': []}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None,
     'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
     'in_reply_to_screen_name': None,
     'user': {'id': 907729752320102400, 'id_str': '907729752320102400', 'name': 'LitecoinUKs',
              'screen_name': 'LitecoinUKs', 'location': 'United Kingdom',
              'description': 'UK based account talking about anything and everything #Litecoin related. If you would like a RT from us please include the hashtag #LitecoinUK',
              'url': 'https://t.co/DqnUBdJbOT', 'entities': {'url': {'urls': [
             {'url': 'https://t.co/DqnUBdJbOT', 'expanded_url': 'https://t.me/iCenter_Lite_BOT?start=4mph0w2552',
              'display_url': 't.me/iCenter_Lite_B…', 'indices': [0, 23]}]}, 'description': {'urls': []}},
              'protected': False, 'followers_count': 2581, 'friends_count': 2847, 'listed_count': 21,
              'created_at': 'Tue Sep 12 22:16:52 +0000 2017', 'favourites_count': 64, 'utc_offset': None,
              'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 27775, 'lang': 'en',
              'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
              'profile_background_color': 'F5F8FA', 'profile_background_image_url': None,
              'profile_background_image_url_https': None, 'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/907730390168883201/kGvZ9avz_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/907730390168883201/kGvZ9avz_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/907729752320102400/1505254877',
              'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
              'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'retweeted_status': {'created_at': 'Sat May 12 15:10:52 +0000 2018', 'id': 995320411301675009,
                          'id_str': '995320411301675009',
                          'text': '#Bitcoin prices through the years $0.0001 to $8,500 2009-2018 #crypto #cryptocurreny #ether #litecoin https://t.co/2iesH6n4T1',
                          'truncated': False, 'entities': {
             'hashtags': [{'text': 'Bitcoin', 'indices': [0, 8]}, {'text': 'crypto', 'indices': [62, 69]},
                          {'text': 'cryptocurreny', 'indices': [70, 84]}, {'text': 'ether', 'indices': [85, 91]},
                          {'text': 'litecoin', 'indices': [92, 101]}], 'symbols': [], 'user_mentions': [], 'urls': [
                 {'url': 'https://t.co/2iesH6n4T1',
                  'expanded_url': 'https://twitter.com/blckchaindaily/status/988597541955624960',
                  'display_url': 'twitter.com/blckchaindaily…', 'indices': [102, 125]}]},
                          'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
                          'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                          'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                          'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
                          'user': {'id': 15223998, 'id_str': '15223998', 'name': 'Rafael Solis',
                                   'screen_name': 'rafaelsolis', 'location': 'San Francisco',
                                   'description': 'Co-Founder @braidthis (collaborative learning platform). Integrating learning into your everyday workflow. Strategic Business & Marketing Nerd.',
                                   'url': 'http://t.co/7Sict2UTAT', 'entities': {'url': {'urls': [
                                  {'url': 'http://t.co/7Sict2UTAT', 'expanded_url': 'http://about.me/RafaelSolis',
                                   'display_url': 'about.me/RafaelSolis', 'indices': [0, 22]}]},
                                                                                 'description': {'urls': []}},
                                   'protected': False, 'followers_count': 396, 'friends_count': 834, 'listed_count': 51,
                                   'created_at': 'Tue Jun 24 20:59:08 +0000 2008', 'favourites_count': 646,
                                   'utc_offset': -25200, 'time_zone': 'Pacific Time (US & Canada)', 'geo_enabled': True,
                                   'verified': False, 'statuses_count': 2358, 'lang': 'en',
                                   'contributors_enabled': False, 'is_translator': False,
                                   'is_translation_enabled': False, 'profile_background_color': 'DEBCE8',
                                   'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/810381157/4eff93190d5ef9080c0fd5175cbc568a.jpeg',
                                   'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/810381157/4eff93190d5ef9080c0fd5175cbc568a.jpeg',
                                   'profile_background_tile': True,
                                   'profile_image_url': 'http://pbs.twimg.com/profile_images/487301785371934720/pZsMQ0in_normal.jpeg',
                                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/487301785371934720/pZsMQ0in_normal.jpeg',
                                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/15223998/1505767255',
                                   'profile_link_color': '379196', 'profile_sidebar_border_color': '000000',
                                   'profile_sidebar_fill_color': '2E2B36', 'profile_text_color': '575E5E',
                                   'profile_use_background_image': True, 'has_extended_profile': False,
                                   'default_profile': False, 'default_profile_image': False, 'following': False,
                                   'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                          'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                          'is_quote_status': True, 'quoted_status_id': 988597541955624960,
                          'quoted_status_id_str': '988597541955624960',
                          'quoted_status': {'created_at': 'Tue Apr 24 01:56:35 +0000 2018', 'id': 988597541955624960,
                                            'id_str': '988597541955624960',
                                            'text': 'The Price of One #Bitcoin Through the Years. https://t.co/tLNIUFHCvE',
                                            'truncated': False,
                                            'entities': {'hashtags': [{'text': 'Bitcoin', 'indices': [17, 25]}],
                                                         'symbols': [], 'user_mentions': [], 'urls': [], 'media': [
                                                    {'id': 988597491527573505, 'id_str': '988597491527573505',
                                                     'indices': [45, 68],
                                                     'media_url': 'http://pbs.twimg.com/media/Dbg0LkRX4AEJnWT.jpg',
                                                     'media_url_https': 'https://pbs.twimg.com/media/Dbg0LkRX4AEJnWT.jpg',
                                                     'url': 'https://t.co/tLNIUFHCvE',
                                                     'display_url': 'pic.twitter.com/tLNIUFHCvE',
                                                     'expanded_url': 'https://twitter.com/blckchaindaily/status/988597541955624960/photo/1',
                                                     'type': 'photo',
                                                     'sizes': {'medium': {'w': 1122, 'h': 861, 'resize': 'fit'},
                                                               'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                               'large': {'w': 1122, 'h': 861, 'resize': 'fit'},
                                                               'small': {'w': 680, 'h': 522, 'resize': 'fit'}}}]},
                                            'extended_entities': {'media': [
                                                {'id': 988597491527573505, 'id_str': '988597491527573505',
                                                 'indices': [45, 68],
                                                 'media_url': 'http://pbs.twimg.com/media/Dbg0LkRX4AEJnWT.jpg',
                                                 'media_url_https': 'https://pbs.twimg.com/media/Dbg0LkRX4AEJnWT.jpg',
                                                 'url': 'https://t.co/tLNIUFHCvE',
                                                 'display_url': 'pic.twitter.com/tLNIUFHCvE',
                                                 'expanded_url': 'https://twitter.com/blckchaindaily/status/988597541955624960/photo/1',
                                                 'type': 'photo',
                                                 'sizes': {'medium': {'w': 1122, 'h': 861, 'resize': 'fit'},
                                                           'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                           'large': {'w': 1122, 'h': 861, 'resize': 'fit'},
                                                           'small': {'w': 680, 'h': 522, 'resize': 'fit'}}}]},
                                            'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
                                            'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                                            'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None,
                                            'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
                                            'in_reply_to_screen_name': None,
                                            'user': {'id': 909594463214931968, 'id_str': '909594463214931968',
                                                     'name': 'Blockchain Daily', 'screen_name': 'blckchaindaily',
                                                     'location': 'Worldwide',
                                                     'description': 'Your Foremost Source for #Blockchain News.',
                                                     'url': 'https://t.co/p5KGU4iVHr', 'entities': {'url': {'urls': [
                                                    {'url': 'https://t.co/p5KGU4iVHr',
                                                     'expanded_url': 'http://blockchaindaily.news',
                                                     'display_url': 'blockchaindaily.news', 'indices': [0, 23]}]},
                                                                                                    'description': {
                                                                                                        'urls': []}},
                                                     'protected': False, 'followers_count': 6161, 'friends_count': 6592,
                                                     'listed_count': 81, 'created_at': 'Mon Sep 18 01:46:34 +0000 2017',
                                                     'favourites_count': 59478, 'utc_offset': None, 'time_zone': None,
                                                     'geo_enabled': False, 'verified': False, 'statuses_count': 954,
                                                     'lang': 'en', 'contributors_enabled': False,
                                                     'is_translator': False, 'is_translation_enabled': False,
                                                     'profile_background_color': '000000',
                                                     'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                                     'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                                     'profile_background_tile': False,
                                                     'profile_image_url': 'http://pbs.twimg.com/profile_images/985187956087574529/2dfLDnkm_normal.jpg',
                                                     'profile_image_url_https': 'https://pbs.twimg.com/profile_images/985187956087574529/2dfLDnkm_normal.jpg',
                                                     'profile_banner_url': 'https://pbs.twimg.com/profile_banners/909594463214931968/1523598207',
                                                     'profile_link_color': '1B95E0',
                                                     'profile_sidebar_border_color': '000000',
                                                     'profile_sidebar_fill_color': '000000',
                                                     'profile_text_color': '000000',
                                                     'profile_use_background_image': False,
                                                     'has_extended_profile': False, 'default_profile': False,
                                                     'default_profile_image': False, 'following': False,
                                                     'follow_request_sent': False, 'notifications': False,
                                                     'translator_type': 'none'}, 'geo': None, 'coordinates': None,
                                            'place': None, 'contributors': None, 'is_quote_status': False,
                                            'retweet_count': 28, 'favorite_count': 45, 'favorited': False,
                                            'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
                          'retweet_count': 1, 'favorite_count': 1, 'favorited': False, 'retweeted': False,
                          'possibly_sensitive': False, 'lang': 'en'}, 'is_quote_status': True,
     'quoted_status_id': 988597541955624960, 'quoted_status_id_str': '988597541955624960', 'retweet_count': 1,
     'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'en'},
    {'created_at': 'Sat May 12 15:29:13 +0000 2018', 'id': 995325025845764098, 'id_str': '995325025845764098',
     'text': 'RT @RoccoDallas: Native Litecoin [LTC] transactions and USD wire support will be available on ABRA https://t.co/RgP7cC4JcS',
     'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
        {'screen_name': 'RoccoDallas', 'name': 'BitTrail', 'id': 288638912, 'id_str': '288638912', 'indices': [3, 15]}],
                                      'urls': [
                                          {'url': 'https://t.co/RgP7cC4JcS', 'expanded_url': 'https://goo.gl/Nu2Q7z',
                                           'display_url': 'goo.gl/Nu2Q7z', 'indices': [99, 122]}]},
     'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
     'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
     'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
     'user': {'id': 521099496, 'id_str': '521099496', 'name': 'Jose Manuel Avelino', 'screen_name': 'XoceAve',
              'location': 'España',
              'description': 'Blockchain enthusiastic, future technologies and AI Dev. Industrial project senior manager',
              'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 30,
              'friends_count': 157, 'listed_count': 1, 'created_at': 'Sun Mar 11 07:24:26 +0000 2012',
              'favourites_count': 10, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False,
              'statuses_count': 689, 'lang': 'es', 'contributors_enabled': False, 'is_translator': False,
              'is_translation_enabled': False, 'profile_background_color': 'C0DEED',
              'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
              'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
              'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/895667734595457024/sm_0FMDk_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/895667734595457024/sm_0FMDk_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/521099496/1502378850',
              'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
              'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': True,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'retweeted_status': {'created_at': 'Sat May 12 11:42:04 +0000 2018', 'id': 995267865442832384,
                          'id_str': '995267865442832384',
                          'text': 'Native Litecoin [LTC] transactions and USD wire support will be available on ABRA https://t.co/RgP7cC4JcS',
                          'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
             {'url': 'https://t.co/RgP7cC4JcS', 'expanded_url': 'https://goo.gl/Nu2Q7z', 'display_url': 'goo.gl/Nu2Q7z',
              'indices': [82, 105]}]}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
                          'source': '<a href="https://dlvrit.com/" rel="nofollow">dlvr.it</a>',
                          'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                          'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
                          'user': {'id': 288638912, 'id_str': '288638912', 'name': 'BitTrail',
                                   'screen_name': 'RoccoDallas', 'location': 'Dubai, UAE',
                                   'description': 'Automated posts From wide range of Mainstream Media and public sources, monitoring sentiment of emerging #Crypto Markets.',
                                   'url': None, 'entities': {'description': {'urls': []}}, 'protected': False,
                                   'followers_count': 1811, 'friends_count': 164, 'listed_count': 70,
                                   'created_at': 'Wed Apr 27 06:25:55 +0000 2011', 'favourites_count': 73,
                                   'utc_offset': 14400, 'time_zone': 'Muscat', 'geo_enabled': False, 'verified': False,
                                   'statuses_count': 200085, 'lang': 'en', 'contributors_enabled': False,
                                   'is_translator': False, 'is_translation_enabled': False,
                                   'profile_background_color': 'FFFFFF',
                                   'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/244273077/yallatime2.jpg',
                                   'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/244273077/yallatime2.jpg',
                                   'profile_background_tile': False,
                                   'profile_image_url': 'http://pbs.twimg.com/profile_images/913636712647184385/bPLKv4Eb_normal.jpg',
                                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/913636712647184385/bPLKv4Eb_normal.jpg',
                                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/288638912/1506672912',
                                   'profile_link_color': '0084B4', 'profile_sidebar_border_color': 'C0DEED',
                                   'profile_sidebar_fill_color': 'F5F3DC', 'profile_text_color': '333333',
                                   'profile_use_background_image': False, 'has_extended_profile': False,
                                   'default_profile': False, 'default_profile_image': False, 'following': False,
                                   'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                          'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                          'is_quote_status': False, 'retweet_count': 2, 'favorite_count': 1, 'favorited': False,
                          'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}, 'is_quote_status': False,
     'retweet_count': 2, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False,
     'lang': 'en'},
    {'created_at': 'Sat May 12 15:29:08 +0000 2018', 'id': 995325007080210434, 'id_str': '995325007080210434',
     'text': '@novogratz @MariaBartiromo @MariaWallStreet Can’t wait for litecoin to rise on the index.',
     'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
        {'screen_name': 'novogratz', 'name': 'Michael Novogratz', 'id': 19847181, 'id_str': '19847181',
         'indices': [0, 10]},
        {'screen_name': 'MariaBartiromo', 'name': 'Maria Bartiromo', 'id': 208155240, 'id_str': '208155240',
         'indices': [11, 26]},
        {'screen_name': 'MariaWallStreet', 'name': "Maria Bartiromo's Wall Street", 'id': 59316702,
         'id_str': '59316702', 'indices': [27, 43]}], 'urls': []},
     'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
     'in_reply_to_status_id': 995315628411117569, 'in_reply_to_status_id_str': '995315628411117569',
     'in_reply_to_user_id': 19847181, 'in_reply_to_user_id_str': '19847181', 'in_reply_to_screen_name': 'novogratz',
     'user': {'id': 942252916475179008, 'id_str': '942252916475179008', 'name': 'Litecoin Main [LTC 8k] [BTC 250k]',
              'screen_name': 'xtdisnkfe', 'location': 'United States',
              'description': 'litecoin is like bitcoin but better. Bitcoin and Litecoin are main coins. I’m here to help, learn and share litecoin news as we move towards market adoption',
              'url': 'https://t.co/eHmrPsWm5g', 'entities': {'url': {'urls': [
             {'url': 'https://t.co/eHmrPsWm5g', 'expanded_url': 'http://flappening.watch/',
              'display_url': 'flappening.watch', 'indices': [0, 23]}]}, 'description': {'urls': []}},
              'protected': False, 'followers_count': 204, 'friends_count': 200, 'listed_count': 3,
              'created_at': 'Sun Dec 17 04:39:36 +0000 2017', 'favourites_count': 12157, 'utc_offset': None,
              'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 4127, 'lang': 'en',
              'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
              'profile_background_color': 'F5F8FA', 'profile_background_image_url': None,
              'profile_background_image_url_https': None, 'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/950674847620714501/YOikpbMk_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/950674847620714501/YOikpbMk_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/942252916475179008/1515493548',
              'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
              'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False,
     'lang': 'en'},
    {'created_at': 'Sat May 12 15:29:02 +0000 2018', 'id': 995324980391903232, 'id_str': '995324980391903232',
     'text': "RT @ImpressioLTD: It's perfect that our company's coin is the IMPR token, because we are constantly trying to IMPRove.  Let us know in the…",
     'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
        {'screen_name': 'ImpressioLTD', 'name': 'IMPRESSIO', 'id': 921435783508004864, 'id_str': '921435783508004864',
         'indices': [3, 16]}], 'urls': []}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
     'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
     'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
     'user': {'id': 922478902273908736, 'id_str': '922478902273908736', 'name': 'bhibhiqool',
              'screen_name': 'bhibhiqool', 'location': '', 'description': '', 'url': None,
              'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 2826,
              'friends_count': 3214, 'listed_count': 3, 'created_at': 'Mon Oct 23 15:04:43 +0000 2017',
              'favourites_count': 5009, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': False,
              'statuses_count': 5786, 'lang': 'id', 'contributors_enabled': False, 'is_translator': False,
              'is_translation_enabled': False, 'profile_background_color': 'F5F8FA',
              'profile_background_image_url': None, 'profile_background_image_url_https': None,
              'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/961244556116213760/6WOyPDGi_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/961244556116213760/6WOyPDGi_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/922478902273908736/1518013537',
              'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
              'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'retweeted_status': {'created_at': 'Sun Apr 22 14:23:06 +0000 2018', 'id': 988060630287638528,
                          'id_str': '988060630287638528',
                          'text': "It's perfect that our company's coin is the IMPR token, because we are constantly trying to IMPRove.  Let us know i… https://t.co/gixMKrHqsD",
                          'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
             {'url': 'https://t.co/gixMKrHqsD', 'expanded_url': 'https://twitter.com/i/web/status/988060630287638528',
              'display_url': 'twitter.com/i/web/status/9…', 'indices': [117, 140]}]},
                          'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
                          'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                          'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                          'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
                          'user': {'id': 921435783508004864, 'id_str': '921435783508004864', 'name': 'IMPRESSIO',
                                   'screen_name': 'ImpressioLTD', 'location': 'London, England',
                                   'description': 'CEO - https://t.co/JD0Qpu5hCt', 'url': 'https://t.co/JD0Qpu5hCt',
                                   'entities': {'url': {'urls': [
                                       {'url': 'https://t.co/JD0Qpu5hCt', 'expanded_url': 'http://Impressio.io',
                                        'display_url': 'Impressio.io', 'indices': [0, 23]}]}, 'description': {'urls': [
                                       {'url': 'https://t.co/JD0Qpu5hCt', 'expanded_url': 'http://Impressio.io',
                                        'display_url': 'Impressio.io', 'indices': [6, 29]}]}}, 'protected': False,
                                   'followers_count': 10018, 'friends_count': 6, 'listed_count': 51,
                                   'created_at': 'Fri Oct 20 17:59:45 +0000 2017', 'favourites_count': 26,
                                   'utc_offset': -25200, 'time_zone': 'Pacific Time (US & Canada)',
                                   'geo_enabled': False, 'verified': False, 'statuses_count': 21, 'lang': 'en',
                                   'contributors_enabled': False, 'is_translator': False,
                                   'is_translation_enabled': False, 'profile_background_color': '000000',
                                   'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                   'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                   'profile_background_tile': False,
                                   'profile_image_url': 'http://pbs.twimg.com/profile_images/984708457285799936/89eIrmfU_normal.jpg',
                                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/984708457285799936/89eIrmfU_normal.jpg',
                                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/921435783508004864/1523640102',
                                   'profile_link_color': '1B95E0', 'profile_sidebar_border_color': '000000',
                                   'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
                                   'profile_use_background_image': False, 'has_extended_profile': True,
                                   'default_profile': False, 'default_profile_image': False, 'following': False,
                                   'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                          'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                          'is_quote_status': False, 'retweet_count': 914, 'favorite_count': 1016, 'favorited': False,
                          'retweeted': False, 'lang': 'en'}, 'is_quote_status': False, 'retweet_count': 914,
     'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'en'},
    {'created_at': 'Sat May 12 15:28:22 +0000 2018', 'id': 995324813689339904, 'id_str': '995324813689339904',
     'text': 'New post (Litecoin [LTC] Has Reasons To Celebrate Despite The Price Crash – Crypto Recorder) has been published on… https://t.co/s1hPTYsOyl',
     'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
        {'url': 'https://t.co/s1hPTYsOyl', 'expanded_url': 'https://twitter.com/i/web/status/995324813689339904',
         'display_url': 'twitter.com/i/web/status/9…', 'indices': [116, 139]}]},
     'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="https://cryptnus.com/" rel="nofollow">auto poster cryptnus</a>', 'in_reply_to_status_id': None,
     'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
     'in_reply_to_screen_name': None,
     'user': {'id': 970111438357450752, 'id_str': '970111438357450752', 'name': 'Cryptnus', 'screen_name': 'cryptnus',
              'location': 'Ottawa, Ontario', 'description': 'Check out https://t.co/BW6P1cqutI', 'url': None,
              'entities': {'description': {'urls': [
                  {'url': 'https://t.co/BW6P1cqutI', 'expanded_url': 'http://cryptnus.com',
                   'display_url': 'cryptnus.com', 'indices': [10, 33]}]}}, 'protected': False, 'followers_count': 63,
              'friends_count': 49, 'listed_count': 2, 'created_at': 'Sun Mar 04 01:39:25 +0000 2018',
              'favourites_count': 3, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False,
              'statuses_count': 3670, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False,
              'is_translation_enabled': False, 'profile_background_color': 'F5F8FA',
              'profile_background_image_url': None, 'profile_background_image_url_https': None,
              'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/970113587778850816/OtjBycCr_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/970113587778850816/OtjBycCr_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/970111438357450752/1520128079',
              'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
              'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False,
     'possibly_sensitive': False, 'lang': 'en'},
    {'created_at': 'Sat May 12 15:28:14 +0000 2018', 'id': 995324780369793025, 'id_str': '995324780369793025',
     'text': 'RT @Peurtoken: https://t.co/oXIXJbYU9R marketplace service provider benefit:\n\n√ Service provider protection insurance available through Peu…',
     'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
        {'screen_name': 'Peurtoken', 'name': 'Peur Token', 'id': 931731798186377216, 'id_str': '931731798186377216',
         'indices': [3, 13]}], 'urls': [
        {'url': 'https://t.co/oXIXJbYU9R', 'expanded_url': 'https://Peur.io', 'display_url': 'Peur.io',
         'indices': [15, 38]}]}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Lite</a>', 'in_reply_to_status_id': None,
     'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
     'in_reply_to_screen_name': None,
     'user': {'id': 845637619841208325, 'id_str': '845637619841208325', 'name': 'Francheska Santiago',
              'screen_name': 'Fsbs25', 'location': 'Greenhills Manila Philippines', 'description': '', 'url': None,
              'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 17, 'friends_count': 94,
              'listed_count': 0, 'created_at': 'Sat Mar 25 14:04:54 +0000 2017', 'favourites_count': 215,
              'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 314,
              'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
              'profile_background_color': 'F5F8FA', 'profile_background_image_url': None,
              'profile_background_image_url_https': None, 'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/980017922910298112/cUZbsqyA_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/980017922910298112/cUZbsqyA_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/845637619841208325/1522489467',
              'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
              'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'retweeted_status': {'created_at': 'Fri May 11 16:56:38 +0000 2018', 'id': 994984638010413056,
                          'id_str': '994984638010413056',
                          'text': 'https://t.co/oXIXJbYU9R marketplace service provider benefit:\n\n√ Service provider protection insurance available th… https://t.co/IwA3IY8joX',
                          'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
             {'url': 'https://t.co/oXIXJbYU9R', 'expanded_url': 'https://Peur.io', 'display_url': 'Peur.io',
              'indices': [0, 23]},
             {'url': 'https://t.co/IwA3IY8joX', 'expanded_url': 'https://twitter.com/i/web/status/994984638010413056',
              'display_url': 'twitter.com/i/web/status/9…', 'indices': [117, 140]}]},
                          'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
                          'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
                          'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                          'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
                          'user': {'id': 931731798186377216, 'id_str': '931731798186377216', 'name': 'Peur Token',
                                   'screen_name': 'Peurtoken', 'location': 'Australia',
                                   'description': 'Peur is a truly decentralized marketplace and used as payroll  integration.\n#ICO #ERC20 #Ethereum #Bitcoin #LTC #DASH #Blockchain #Cryptocurrency #Peurtoken',
                                   'url': 'https://t.co/TCZpW8ibLR', 'entities': {'url': {'urls': [
                                  {'url': 'https://t.co/TCZpW8ibLR', 'expanded_url': 'https://www.peur.io',
                                   'display_url': 'peur.io', 'indices': [0, 23]}]}, 'description': {'urls': []}},
                                   'protected': False, 'followers_count': 5036, 'friends_count': 860,
                                   'listed_count': 134, 'created_at': 'Sat Nov 18 03:52:26 +0000 2017',
                                   'favourites_count': 1164, 'utc_offset': 36000, 'time_zone': 'Sydney',
                                   'geo_enabled': False, 'verified': False, 'statuses_count': 174, 'lang': 'en',
                                   'contributors_enabled': False, 'is_translator': False,
                                   'is_translation_enabled': False, 'profile_background_color': 'F5F8FA',
                                   'profile_background_image_url': None, 'profile_background_image_url_https': None,
                                   'profile_background_tile': False,
                                   'profile_image_url': 'http://pbs.twimg.com/profile_images/954810233636859904/FLS_EUNN_normal.jpg',
                                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/954810233636859904/FLS_EUNN_normal.jpg',
                                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/931731798186377216/1524679501',
                                   'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                                   'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                                   'profile_use_background_image': True, 'has_extended_profile': False,
                                   'default_profile': True, 'default_profile_image': False, 'following': False,
                                   'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                          'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                          'is_quote_status': False, 'retweet_count': 1321, 'favorite_count': 1082, 'favorited': False,
                          'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}, 'is_quote_status': False,
     'retweet_count': 1321, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False,
     'lang': 'en'},
    {'created_at': 'Sat May 12 15:28:03 +0000 2018', 'id': 995324734693834752, 'id_str': '995324734693834752',
     'text': '@Jamestown502 Yes GUAP coin is a digital coin like bitcoin ethereum &amp; litecoin. She’s raising funds to get it on the crypto index',
     'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
        {'screen_name': 'Jamestown502', 'name': 'Jamestown', 'id': 18297767, 'id_str': '18297767', 'indices': [0, 13]}],
                                      'urls': []}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
     'in_reply_to_status_id': 995324105808334849, 'in_reply_to_status_id_str': '995324105808334849',
     'in_reply_to_user_id': 18297767, 'in_reply_to_user_id_str': '18297767', 'in_reply_to_screen_name': 'Jamestown502',
     'user': {'id': 14963218, 'id_str': '14963218', 'name': 'AngieC', 'screen_name': 'AngieCowan', 'location': 'FLA',
              'description': 'After silence, that which comes nearest to expressing the inexpressible is music.',
              'url': 'https://t.co/zPGCKSJSkg', 'entities': {'url': {'urls': [
             {'url': 'https://t.co/zPGCKSJSkg', 'expanded_url': 'http://www.agcmediagroup.com',
              'display_url': 'agcmediagroup.com', 'indices': [0, 23]}]}, 'description': {'urls': []}},
              'protected': False, 'followers_count': 192, 'friends_count': 141, 'listed_count': 8,
              'created_at': 'Sat May 31 13:59:07 +0000 2008', 'favourites_count': 391, 'utc_offset': -14400,
              'time_zone': 'Eastern Time (US & Canada)', 'geo_enabled': False, 'verified': False,
              'statuses_count': 5195, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False,
              'is_translation_enabled': False, 'profile_background_color': '000000',
              'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/281853952/x7757d4ec9a595deb352fce64867be3f.jpg',
              'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/281853952/x7757d4ec9a595deb352fce64867be3f.jpg',
              'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/856246158590660615/1yGeLI1g_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/856246158590660615/1yGeLI1g_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/14963218/1492979826',
              'profile_link_color': 'FB840E', 'profile_sidebar_border_color': '373737',
              'profile_sidebar_fill_color': '373737', 'profile_text_color': 'FDB31C',
              'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False,
     'lang': 'en'},
    {'created_at': 'Sat May 12 15:27:37 +0000 2018', 'id': 995324625679773696, 'id_str': '995324625679773696',
     'text': '@hotmonkeydeals Pin this tweet- you will hugely regret not having any litecoin in approx 3 years',
     'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
        {'screen_name': 'hotmonkeydeals', 'name': 'Crypto Monkey🐒🚀👨\u200d🚀📈[LTC] [TRX] [VEN]', 'id': 2709195090,
         'id_str': '2709195090', 'indices': [0, 15]}], 'urls': []},
     'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
     'in_reply_to_status_id': 995317554754277376, 'in_reply_to_status_id_str': '995317554754277376',
     'in_reply_to_user_id': 2709195090, 'in_reply_to_user_id_str': '2709195090',
     'in_reply_to_screen_name': 'hotmonkeydeals',
     'user': {'id': 2283601622, 'id_str': '2283601622', 'name': 'CRYPTO OWΞN (Not Giving Away ETH) WIŁSON',
              'screen_name': 'CryptOwenWilson', 'location': 'This is a Parody Account.',
              'description': 'Wow!!! | Full Time Crypto | Blockchain Technology is Incredible | Not Financial Advice',
              'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 6039,
              'friends_count': 705, 'listed_count': 41, 'created_at': 'Thu Jan 09 13:43:59 +0000 2014',
              'favourites_count': 17515, 'utc_offset': -14400, 'time_zone': 'Indiana (East)', 'geo_enabled': False,
              'verified': False, 'statuses_count': 9820, 'lang': 'en', 'contributors_enabled': False,
              'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000',
              'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
              'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
              'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/994800333598724096/AJ_EmrAh_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/994800333598724096/AJ_EmrAh_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2283601622/1526013388',
              'profile_link_color': 'FF691F', 'profile_sidebar_border_color': '000000',
              'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
              'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False,
     'lang': 'en'},
    {'created_at': 'Sat May 12 15:27:33 +0000 2018', 'id': 995324607384010754, 'id_str': '995324607384010754',
     'text': 'RT @billbarhydt: #Monero (XMR), #NEO (NEO), #NEM (XEM), #Lisk (LSK), and #Verge (XVG) are now live on Abra! 👀 We’re now at 25 cryptocurrenc…',
     'truncated': False, 'entities': {
        'hashtags': [{'text': 'Monero', 'indices': [17, 24]}, {'text': 'NEO', 'indices': [32, 36]},
                     {'text': 'NEM', 'indices': [44, 48]}, {'text': 'Lisk', 'indices': [56, 61]},
                     {'text': 'Verge', 'indices': [73, 79]}], 'symbols': [], 'user_mentions': [
            {'screen_name': 'billbarhydt', 'name': 'Bill Barhydt', 'id': 896141, 'id_str': '896141',
             'indices': [3, 15]}], 'urls': []}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
     'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
     'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
     'user': {'id': 937937990621335554, 'id_str': '937937990621335554', 'name': 'Evan {LTC}',
              'screen_name': 'LitecoinEazyE', 'location': '',
              'description': '#litecoinnation #litecoinfam #paywithlitecoin', 'url': None,
              'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 199,
              'friends_count': 129, 'listed_count': 2, 'created_at': 'Tue Dec 05 06:53:37 +0000 2017',
              'favourites_count': 2365, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False,
              'statuses_count': 753, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False,
              'is_translation_enabled': False, 'profile_background_color': 'F5F8FA',
              'profile_background_image_url': None, 'profile_background_image_url_https': None,
              'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/993598052333109248/uCC-3-aJ_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/993598052333109248/uCC-3-aJ_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/937937990621335554/1520701762',
              'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
              'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'retweeted_status': {'created_at': 'Fri May 11 14:05:40 +0000 2018', 'id': 994941613326651392,
                          'id_str': '994941613326651392',
                          'text': '#Monero (XMR), #NEO (NEO), #NEM (XEM), #Lisk (LSK), and #Verge (XVG) are now live on Abra! 👀 We’re now at 25 crypto… https://t.co/hmqUV0Bucx',
                          'truncated': True, 'entities': {
             'hashtags': [{'text': 'Monero', 'indices': [0, 7]}, {'text': 'NEO', 'indices': [15, 19]},
                          {'text': 'NEM', 'indices': [27, 31]}, {'text': 'Lisk', 'indices': [39, 44]},
                          {'text': 'Verge', 'indices': [56, 62]}], 'symbols': [], 'user_mentions': [], 'urls': [
                 {'url': 'https://t.co/hmqUV0Bucx',
                  'expanded_url': 'https://twitter.com/i/web/status/994941613326651392',
                  'display_url': 'twitter.com/i/web/status/9…', 'indices': [117, 140]}]},
                          'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
                          'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                          'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                          'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
                          'user': {'id': 896141, 'id_str': '896141', 'name': 'Bill Barhydt',
                                   'screen_name': 'billbarhydt', 'location': 'Mountain View, CA',
                                   'description': 'CEO & Founder @AbraGlobal. F1 driver and alpine ski racer wannabe. Bringing Bitcoin and Crypto Investing to the World!',
                                   'url': 'https://t.co/IV6gs3TemK', 'entities': {'url': {'urls': [
                                  {'url': 'https://t.co/IV6gs3TemK', 'expanded_url': 'https://abra.com/get_bb',
                                   'display_url': 'abra.com/get_bb', 'indices': [0, 23]}]},
                                                                                  'description': {'urls': []}},
                                   'protected': False, 'followers_count': 12412, 'friends_count': 282,
                                   'listed_count': 426, 'created_at': 'Sun Mar 11 02:34:59 +0000 2007',
                                   'favourites_count': 17596, 'utc_offset': -25200,
                                   'time_zone': 'Pacific Time (US & Canada)', 'geo_enabled': True, 'verified': False,
                                   'statuses_count': 11483, 'lang': 'en', 'contributors_enabled': False,
                                   'is_translator': False, 'is_translation_enabled': False,
                                   'profile_background_color': '9AE4E8',
                                   'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/434877321846067200/3pRVYtOb.jpeg',
                                   'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/434877321846067200/3pRVYtOb.jpeg',
                                   'profile_background_tile': True,
                                   'profile_image_url': 'http://pbs.twimg.com/profile_images/848707856605917184/CJAVu7HY_normal.jpg',
                                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/848707856605917184/CJAVu7HY_normal.jpg',
                                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/896141/1474277815',
                                   'profile_link_color': '0000FF', 'profile_sidebar_border_color': 'FFFFFF',
                                   'profile_sidebar_fill_color': 'E0FF92', 'profile_text_color': '000000',
                                   'profile_use_background_image': True, 'has_extended_profile': True,
                                   'default_profile': False, 'default_profile_image': False, 'following': False,
                                   'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                          'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                          'is_quote_status': False, 'retweet_count': 199, 'favorite_count': 622, 'favorited': False,
                          'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}, 'is_quote_status': False,
     'retweet_count': 199, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'en'},
    {'created_at': 'Sat May 12 15:27:31 +0000 2018', 'id': 995324600870363136, 'id_str': '995324600870363136',
     'text': 'RT @GadgTecs: Get FREE bitcoins worth $10 + A free and secure bitcoin, ethereum and litecoin wallet by Coinbase (voted the best wallet for…',
     'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
        {'screen_name': 'GadgTecs', 'name': 'GadgTecs', 'id': 1074705456, 'id_str': '1074705456', 'indices': [3, 12]}],
                                      'urls': []}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
     'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
     'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
     'user': {'id': 4611371654, 'id_str': '4611371654', 'name': 'Arun Karthik C', 'screen_name': 'Arunkarthikc007',
              'location': 'Garden city',
              'description': 'Partner @ Softriskex advisory solutions !*!\nHelping in rising funds for New Entrepreneurs!\nGraduated in Jain University!#!\nDiplomat in Finance & Marketing',
              'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 1445,
              'friends_count': 798, 'listed_count': 398, 'created_at': 'Sun Dec 20 10:02:09 +0000 2015',
              'favourites_count': 1930, 'utc_offset': -25200, 'time_zone': 'Pacific Time (US & Canada)',
              'geo_enabled': False, 'verified': False, 'statuses_count': 48816, 'lang': 'en',
              'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
              'profile_background_color': 'FFF04D',
              'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme19/bg.gif',
              'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme19/bg.gif',
              'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/985091036941881344/srP3cHEr_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/985091036941881344/srP3cHEr_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/4611371654/1452782466',
              'profile_link_color': '0099CC', 'profile_sidebar_border_color': 'FFF8AD',
              'profile_sidebar_fill_color': 'F6FFD1', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': False,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'retweeted_status': {'created_at': 'Sat May 12 13:47:03 +0000 2018', 'id': 995299315512958978,
                          'id_str': '995299315512958978',
                          'text': 'Get FREE bitcoins worth $10 + A free and secure bitcoin, ethereum and litecoin wallet by Coinbase (voted the best w… https://t.co/xGoU7zp1qT',
                          'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
             {'url': 'https://t.co/xGoU7zp1qT', 'expanded_url': 'https://twitter.com/i/web/status/995299315512958978',
              'display_url': 'twitter.com/i/web/status/9…', 'indices': [117, 140]}]},
                          'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
                          'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                          'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                          'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
                          'user': {'id': 1074705456, 'id_str': '1074705456', 'name': 'GadgTecs',
                                   'screen_name': 'GadgTecs', 'location': 'United States',
                                   'description': 'We love #Technology - Follow 4 amazing DIY n creative pics, videos, gadgets & trends.    #Science #Tech #Gadgets #Educational, #WebDesign #Marketing #Followback',
                                   'url': 'http://t.co/QsDuJ2yOCX', 'entities': {'url': {'urls': [
                                  {'url': 'http://t.co/QsDuJ2yOCX', 'expanded_url': 'http://gadgtecs.com',
                                   'display_url': 'gadgtecs.com', 'indices': [0, 22]}]}, 'description': {'urls': []}},
                                   'protected': False, 'followers_count': 36311, 'friends_count': 29468,
                                   'listed_count': 423, 'created_at': 'Wed Jan 09 19:49:08 +0000 2013',
                                   'favourites_count': 67818, 'utc_offset': 18000, 'time_zone': 'Asia/Karachi',
                                   'geo_enabled': True, 'verified': False, 'statuses_count': 1698, 'lang': 'en',
                                   'contributors_enabled': False, 'is_translator': False,
                                   'is_translation_enabled': False, 'profile_background_color': '000000',
                                   'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/602877067248607232/jQStP49t.jpg',
                                   'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/602877067248607232/jQStP49t.jpg',
                                   'profile_background_tile': True,
                                   'profile_image_url': 'http://pbs.twimg.com/profile_images/779405762368077824/PC00314j_normal.jpg',
                                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/779405762368077824/PC00314j_normal.jpg',
                                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1074705456/1518359248',
                                   'profile_link_color': 'ABB8C2', 'profile_sidebar_border_color': '000000',
                                   'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
                                   'profile_use_background_image': True, 'has_extended_profile': False,
                                   'default_profile': False, 'default_profile_image': False, 'following': False,
                                   'follow_request_sent': False, 'notifications': False, 'translator_type': 'regular'},
                          'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                          'is_quote_status': False, 'retweet_count': 4, 'favorite_count': 4, 'favorited': False,
                          'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}, 'is_quote_status': False,
     'retweet_count': 4, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'en'},
    {'created_at': 'Sat May 12 15:27:23 +0000 2018', 'id': 995324564304363521, 'id_str': '995324564304363521',
     'text': "RT @drhmarahman: 'Mine whatever you want to Mine'. The first historical crypto mining operation in the world\nhttps://t.co/9h8fAssxlf\n\n#mini…",
     'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
        {'screen_name': 'drhmarahman', 'name': 'HM A Rahman', 'id': 930108632984821761, 'id_str': '930108632984821761',
         'indices': [3, 15]}], 'urls': [
        {'url': 'https://t.co/9h8fAssxlf', 'expanded_url': 'https://miniera.io/', 'display_url': 'miniera.io',
         'indices': [109, 132]}]}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None,
     'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
     'in_reply_to_screen_name': None,
     'user': {'id': 906348094689648640, 'id_str': '906348094689648640', 'name': 'nguyen trung tho',
              'screen_name': 'nguyent60928957', 'location': '', 'description': '', 'url': None,
              'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 18,
              'friends_count': 580, 'listed_count': 0, 'created_at': 'Sat Sep 09 02:46:39 +0000 2017',
              'favourites_count': 95, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False,
              'statuses_count': 126, 'lang': 'vi', 'contributors_enabled': False, 'is_translator': False,
              'is_translation_enabled': False, 'profile_background_color': 'F5F8FA',
              'profile_background_image_url': None, 'profile_background_image_url_https': None,
              'profile_background_tile': False,
              'profile_image_url': 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
              'profile_image_url_https': 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
              'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
              'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
              'default_profile_image': True, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'retweeted_status': {'created_at': 'Thu May 10 10:21:39 +0000 2018', 'id': 994522848600375297,
                          'id_str': '994522848600375297',
                          'text': "'Mine whatever you want to Mine'. The first historical crypto mining operation in the world\nhttps://t.co/9h8fAssxlf… https://t.co/rqueiqVg7W",
                          'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
             {'url': 'https://t.co/9h8fAssxlf', 'expanded_url': 'https://miniera.io/', 'display_url': 'miniera.io',
              'indices': [92, 115]},
             {'url': 'https://t.co/rqueiqVg7W', 'expanded_url': 'https://twitter.com/i/web/status/994522848600375297',
              'display_url': 'twitter.com/i/web/status/9…', 'indices': [117, 140]}]},
                          'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
                          'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                          'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                          'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
                          'user': {'id': 930108632984821761, 'id_str': '930108632984821761', 'name': 'HM A Rahman',
                                   'screen_name': 'drhmarahman', 'location': 'Dhaka, Bangladesh',
                                   'description': 'Do you want to promote your ico, crypto, btc or any cryptocurrency by social media marketing ?\nIt is the right place.',
                                   'url': None, 'entities': {'description': {'urls': []}}, 'protected': False,
                                   'followers_count': 198, 'friends_count': 262, 'listed_count': 0,
                                   'created_at': 'Mon Nov 13 16:22:33 +0000 2017', 'favourites_count': 42,
                                   'utc_offset': -25200, 'time_zone': 'Pacific Time (US & Canada)', 'geo_enabled': True,
                                   'verified': False, 'statuses_count': 342, 'lang': 'en',
                                   'contributors_enabled': False, 'is_translator': False,
                                   'is_translation_enabled': False, 'profile_background_color': 'F5F8FA',
                                   'profile_background_image_url': None, 'profile_background_image_url_https': None,
                                   'profile_background_tile': False,
                                   'profile_image_url': 'http://pbs.twimg.com/profile_images/950254591051841537/hdru0EDq_normal.jpg',
                                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/950254591051841537/hdru0EDq_normal.jpg',
                                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/930108632984821761/1523217292',
                                   'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                                   'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                                   'profile_use_background_image': True, 'has_extended_profile': True,
                                   'default_profile': True, 'default_profile_image': False, 'following': False,
                                   'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                          'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                          'is_quote_status': False, 'retweet_count': 385, 'favorite_count': 78, 'favorited': False,
                          'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}, 'is_quote_status': False,
     'retweet_count': 385, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False,
     'lang': 'en'},
    {'created_at': 'Sat May 12 15:27:14 +0000 2018', 'id': 995324528912977921, 'id_str': '995324528912977921',
     'text': 'RT @HonestAliHasan: #PerfectMoney U2753675\n#Payeer P4405011\n#Bitcoin 1DXxsKivdJWCmUKSfaERNvVbSh9hzFHx6e\n#BitcoinCash qzyhe87vtphagpqyxhrjns…',
     'truncated': False, 'entities': {
        'hashtags': [{'text': 'PerfectMoney', 'indices': [20, 33]}, {'text': 'Payeer', 'indices': [43, 50]},
                     {'text': 'Bitcoin', 'indices': [60, 68]}, {'text': 'BitcoinCash', 'indices': [104, 116]}],
        'symbols': [], 'user_mentions': [
            {'screen_name': 'HonestAliHasan', 'name': 'Ali Hasan', 'id': 948210755823947776,
             'id_str': '948210755823947776', 'indices': [3, 18]}], 'urls': []},
     'metadata': {'iso_language_code': 'sv', 'result_type': 'recent'},
     'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None,
     'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
     'in_reply_to_screen_name': None,
     'user': {'id': 907729752320102400, 'id_str': '907729752320102400', 'name': 'LitecoinUKs',
              'screen_name': 'LitecoinUKs', 'location': 'United Kingdom',
              'description': 'UK based account talking about anything and everything #Litecoin related. If you would like a RT from us please include the hashtag #LitecoinUK',
              'url': 'https://t.co/DqnUBdJbOT', 'entities': {'url': {'urls': [
             {'url': 'https://t.co/DqnUBdJbOT', 'expanded_url': 'https://t.me/iCenter_Lite_BOT?start=4mph0w2552',
              'display_url': 't.me/iCenter_Lite_B…', 'indices': [0, 23]}]}, 'description': {'urls': []}},
              'protected': False, 'followers_count': 2581, 'friends_count': 2847, 'listed_count': 21,
              'created_at': 'Tue Sep 12 22:16:52 +0000 2017', 'favourites_count': 64, 'utc_offset': None,
              'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 27775, 'lang': 'en',
              'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
              'profile_background_color': 'F5F8FA', 'profile_background_image_url': None,
              'profile_background_image_url_https': None, 'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/907730390168883201/kGvZ9avz_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/907730390168883201/kGvZ9avz_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/907729752320102400/1505254877',
              'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
              'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
              'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'retweeted_status': {'created_at': 'Sat May 12 15:25:41 +0000 2018', 'id': 995324139551514624,
                          'id_str': '995324139551514624',
                          'text': '#PerfectMoney U2753675\n#Payeer P4405011\n#Bitcoin 1DXxsKivdJWCmUKSfaERNvVbSh9hzFHx6e\n#BitcoinCash qzyhe87vtphagpqyxh… https://t.co/75dH0ysrXa',
                          'truncated': True, 'entities': {
             'hashtags': [{'text': 'PerfectMoney', 'indices': [0, 13]}, {'text': 'Payeer', 'indices': [23, 30]},
                          {'text': 'Bitcoin', 'indices': [40, 48]}, {'text': 'BitcoinCash', 'indices': [84, 96]}],
             'symbols': [], 'user_mentions': [], 'urls': [{'url': 'https://t.co/75dH0ysrXa',
                                                           'expanded_url': 'https://twitter.com/i/web/status/995324139551514624',
                                                           'display_url': 'twitter.com/i/web/status/9…',
                                                           'indices': [117, 140]}]},
                          'metadata': {'iso_language_code': 'sv', 'result_type': 'recent'},
                          'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                          'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                          'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
                          'user': {'id': 948210755823947776, 'id_str': '948210755823947776', 'name': 'Ali Hasan',
                                   'screen_name': 'HonestAliHasan', 'location': '',
                                   'description': 'Investment Consultant | Team Builder | Social Media Promoter',
                                   'url': None, 'entities': {'description': {'urls': []}}, 'protected': False,
                                   'followers_count': 425, 'friends_count': 281, 'listed_count': 1,
                                   'created_at': 'Tue Jan 02 15:13:55 +0000 2018', 'favourites_count': 2,
                                   'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False,
                                   'statuses_count': 324, 'lang': 'en', 'contributors_enabled': False,
                                   'is_translator': False, 'is_translation_enabled': False,
                                   'profile_background_color': 'F5F8FA', 'profile_background_image_url': None,
                                   'profile_background_image_url_https': None, 'profile_background_tile': False,
                                   'profile_image_url': 'http://pbs.twimg.com/profile_images/986779267081162753/2gvlKrPJ_normal.jpg',
                                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/986779267081162753/2gvlKrPJ_normal.jpg',
                                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/948210755823947776/1514906585',
                                   'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                                   'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                                   'profile_use_background_image': True, 'has_extended_profile': True,
                                   'default_profile': True, 'default_profile_image': False, 'following': False,
                                   'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                          'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                          'is_quote_status': False, 'retweet_count': 1, 'favorite_count': 0, 'favorited': False,
                          'retweeted': False, 'lang': 'sv'}, 'is_quote_status': False, 'retweet_count': 1,
     'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'sv'},
    {'created_at': 'Sat May 12 15:27:02 +0000 2018', 'id': 995324479772360705, 'id_str': '995324479772360705',
     'text': 'Litecoin [LTC] Has Reasons To Celebrate Despite The Price Crash – Crypto Recorder https://t.co/6BACHNpwLY https://t.co/QBrbQ4krSe',
     'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
        {'url': 'https://t.co/6BACHNpwLY', 'expanded_url': 'http://dlvr.it/QSd965', 'display_url': 'dlvr.it/QSd965',
         'indices': [82, 105]}], 'media': [
        {'id': 995324477255794689, 'id_str': '995324477255794689', 'indices': [106, 129],
         'media_url': 'http://pbs.twimg.com/media/DdAaVq8VQAEfcaT.jpg',
         'media_url_https': 'https://pbs.twimg.com/media/DdAaVq8VQAEfcaT.jpg', 'url': 'https://t.co/QBrbQ4krSe',
         'display_url': 'pic.twitter.com/QBrbQ4krSe',
         'expanded_url': 'https://twitter.com/mycryptonext/status/995324479772360705/photo/1', 'type': 'photo',
         'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 680, 'h': 453, 'resize': 'fit'},
                   'medium': {'w': 800, 'h': 533, 'resize': 'fit'}, 'large': {'w': 800, 'h': 533, 'resize': 'fit'}}}]},
     'extended_entities': {'media': [{'id': 995324477255794689, 'id_str': '995324477255794689', 'indices': [106, 129],
                                      'media_url': 'http://pbs.twimg.com/media/DdAaVq8VQAEfcaT.jpg',
                                      'media_url_https': 'https://pbs.twimg.com/media/DdAaVq8VQAEfcaT.jpg',
                                      'url': 'https://t.co/QBrbQ4krSe', 'display_url': 'pic.twitter.com/QBrbQ4krSe',
                                      'expanded_url': 'https://twitter.com/mycryptonext/status/995324479772360705/photo/1',
                                      'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                                 'small': {'w': 680, 'h': 453, 'resize': 'fit'},
                                                                 'medium': {'w': 800, 'h': 533, 'resize': 'fit'},
                                                                 'large': {'w': 800, 'h': 533, 'resize': 'fit'}}}]},
     'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
     'source': '<a href="https://dlvrit.com/" rel="nofollow">dlvr.it</a>', 'in_reply_to_status_id': None,
     'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
     'in_reply_to_screen_name': None,
     'user': {'id': 973598105814777856, 'id_str': '973598105814777856', 'name': 'Mycryptonext',
              'screen_name': 'mycryptonext', 'location': '', 'description': 'Next Generation Cryptocurrency',
              'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 213,
              'friends_count': 17, 'listed_count': 0, 'created_at': 'Tue Mar 13 16:34:11 +0000 2018',
              'favourites_count': 236, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False,
              'statuses_count': 938, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False,
              'is_translation_enabled': False, 'profile_background_color': '000000',
              'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
              'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
              'profile_background_tile': False,
              'profile_image_url': 'http://pbs.twimg.com/profile_images/978341392220012544/Upd1smDP_normal.jpg',
              'profile_image_url_https': 'https://pbs.twimg.com/profile_images/978341392220012544/Upd1smDP_normal.jpg',
              'profile_banner_url': 'https://pbs.twimg.com/profile_banners/973598105814777856/1522141582',
              'profile_link_color': 'F58EA8', 'profile_sidebar_border_color': '000000',
              'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
              'profile_use_background_image': False, 'has_extended_profile': False, 'default_profile': False,
              'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
              'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
     'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False,
     'possibly_sensitive': False, 'lang': 'en'}],
           'search_metadata': {'completed_in': 0.081, 'max_id': 995325161183350785, 'max_id_str': '995325161183350785',
                               'query': '%2Flitecoin',
                               'refresh_url': '?since_id=995325161183350785&q=%2Flitecoin&include_entities=1',
                               'count': 15, 'since_id': 0, 'since_id_str': '0'}}
